environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10.11"
      PYTHON_ARCH: "64"
  ISS_FILE_PATH: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe"'

platform: x64

configuration: Release

# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true

# Not a project with an msbuild file, build done at install.
build: None

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, check which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"

  # Set the relevant Python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"
  - cmd: pip3 --version
  - ps: python.exe -m pip install --upgrade pip

  # Check out installed python packages
  - cmd: pip3 freeze

install:
  - ps: pip3 install -r requirements.txt
  # PyQt6 installation bug workaround
  - ps: pip3 install --no-cache-dir pyqt6-plugins qt6-applications PyQt6-Qt6 PyQt6-sip pyqt6-tools qt6-tools

  - cmd: pip3 install -U pyinstaller
  - cmd: pyinstaller windows_build.spec

  # Remove unnecessary items
  - cmd: rmdir /s /q dist\main\pyqtgraph\icons
  - cmd: del "dist\main\PyQt6\Qt6\plugins\multimedia\ffmpegmediaplugin.dll"

  # Make installer file
  - cmd: '%ISS_FILE_PATH% Distribution\Windows\eqfreq_AppVeyor.iss'

artifacts:
  - path: Distribution\Windows\output\*.exe

deploy:
  tag: EarQuiz_Frequencies-v$(APPVEYOR_BUILD_VERSION)
  release: draft release of EarQuiz Frequencies -v$(APPVEYOR_BUILD_VERSION)
  description: ''
  provider: GitHub
  auth_token:
    secure: Uzm1JM03aD8x+EeSMyQoUQx9Dmj3DY8GzzOIZ+VEOYFSE+Xrg4eTXQ5FLoPRVwQg
  artifact: /.*\.exe/
  draft: true
  prerelease: true
  on:
    branch: master
  force_update: true
