environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10.11"
      PYTHON_ARCH: "64"
  ISS_FILE_PATH: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe"'

platform: x64

configuration: Release

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, check which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"

  # Set the relevant Python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"
  - cmd: pip3 --version

  # Check out installed python packages
  - cmd: pip3 freeze

install:
  - ps: python.exe -m pip install --upgrade pip
  - ps: pip3 install -r requirements.txt

  - cmd: pip3 install -U pyinstaller
  - cmd: pyinstaller windows_build.spec
  - cmd: '%ISS_FILE_PATH% Distribution\Windows\eqfreq_AppVeyor.iss'

artifacts:
  - path: dist\main
    name: EQ_Freq
  - path: Distribution\Windows\output\*.exe

# Not a project with an msbuild file, build done at install.
build: None

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: draft release of EarQuiz Frequencies -v$(APPVEYOR_BUILD_VERSION)
  description: ''
  provider: GitHub
  auth_token: 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
#    secure: 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
  artifact: /.*\.exe/
  draft: true
  prerelease: true
  on:
#    APPVEYOR_REPO_TAG: true
    branch: master
#    appveyor_repo_tag: true
  force_update: true
