image: macos-monterey

platform: x64

init:
  - chmod +x $HOME/venv3.11/bin/activate
  - source $HOME/venv3.11/bin/activate

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -U pyinstaller
  - pyinstaller macos_build.spec
  - tar -cvf eqfreq_build-macos-x64.tar "dist/EarQuiz Frequencies.app"

build: None

artifacts:
  - path: eqfreq_build-macos-x64.tar

version: 0.1.6 (build-{build})
pull_requests:
  do_not_increment_build_number: true
