environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10.11"
      PYTHON_ARCH: "64"
  ISS_FILE_PATH: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe"'

platform: x64

configuration: Release

# the first failed job cancels other jobs and fails entire build
matrix:
  fast_finish: true

# Not a project with an msbuild file, build done at install.
build: None

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, check which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"

  # Set the relevant Python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"
  - cmd: pip3 --version
  - ps: python.exe -m pip install --upgrade pip

  # Check out installed python packages
  - cmd: pip3 freeze

install:
  - ps: pip3 install -r requirements.txt
  # PyQt6 installation bug workaround
  - ps: pip3 install --no-cache-dir pyqt6-plugins qt6-applications PyQt6-Qt6 PyQt6-sip pyqt6-tools qt6-tools

  - cmd: pip3 install -U pyinstaller
  - cmd: pyinstaller windows_build.spec

  # Remove unnecessary items
  - cmd: rmdir /s /q dist\main\pyqtgraph\icons
  - cmd: del "dist\main\PyQt6\Qt6\plugins\multimedia\ffmpegmediaplugin.dll"

  # Make installer file
  - cmd: '%ISS_FILE_PATH% Distribution\Windows\eqfreq_AppVeyor.iss'

artifacts:
  - path: Distribution\Windows\output\*.exe

version: 0.1.5-build-{build}
pull_requests:
  do_not_increment_build_number: true

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/5d80b854-5feb-4128-ac4c-1ef9a083c0b1/Integrations/AppVeyor?ProjectSlug=EarQuiz_Frequencies&SigningPolicySlug=test-signing&ArtifactConfigurationSlug=initial
  authorization:
    secure: B6b9qk+BJzltehPQLaWiOP8hu5cQEbuHWCkXGFC4xetttaB0dXSbRD+dGt1UTl7LTfJXlIhB9S0FKKjwOLF+Rg==

#deploy:
#  tag: EarQuiz_Frequencies-v$(APPVEYOR_BUILD_VERSION)
#  release: Draft release of EarQuiz Frequencies -v$(APPVEYOR_BUILD_VERSION)
#  description: ''
#  provider: GitHub
#  auth_token:
#    secure: vIMF8qllW0Dd31aDsyEC5PdlzrziLMgeBhXztRsPGttixcu56QhI4otRbUOetxo3
#  artifact: /.*\.exe/
#  draft: true
#  prerelease: true
#  on:
#    branch: master
#  force_update: true
